# Generated by Django 5.0.6 on 2024-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_enquiry_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='pickup_date',
            field=models.CharField(max_length=100),
        ),
    ]
