# Generated by Django 5.0.6 on 2024-05-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_enquiry_mode_alter_enquiry_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='pickup_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='pickup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
