# Generated by Django 5.0.6 on 2024-05-22 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_enquiry_pickup_time_alter_enquiry_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='salesman_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
